import Head from "next/head";
import styles from "../styles/PageLayout.module.css";

export default function PageLayout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.root}>{children}</main>
    </>
  );
}
